#NavyCraft Configuration File
#Written by Solmex

#Defines which worlds the plugin's weapons will funciton in.
EnabledWorlds: WarWorld,BattleWorld,TankSpawn

#Defines which worlds the plugin's battles will funciton in.
BattleWorld: BattleWorld

#Blocks that prevent craft from being created if they are anywhere in the craft leave 'null' for none.
ForbiddenBlocks: 29,33,34,36,52,90,97,116,119,120,130,137,138,145,146

#Any craft types which can drill will eat blocks rather than creating items.
Drill: false

# The amount of output to display to the console.
# 1: Nothing beyond what Bukkit normally does
# 2: Suspected Errors
# 3: Errors and Notifications
# 4: Suspected Errors and Notifications
# 5: Notifications, and Status Messages
LogLevel: 0

#The vehicle only moves if you have the helm.
RequireHelm: false

#The item ID of the item that will control vehicles when a player has the helm.
HelmID: 294

#Are holes allowed in craft (for submarines, drills, etc.)
AllowHoles: false

#The blocks that define the structure of the craft. It is recommended not to use blocks like stone, dirt, and grass.
StructureBlocks: 4,5,14,15,16,17,19,20,21,22,23,25,26,27,28,30,35,41,42,43,44,45,46,47,48,49,50,51,53,54,55,56,57,58,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,79,80,81,82,84,85,86,87,88,89,91,92,93,94,95,96,98,101,102,106,107,108,109,112,113,114,118,121,123,124,125,126,129,131,132,133,134,135,136,139,143,144,147,148,149,150,151,152,153,154,155,156,157,158,159,160,162,163,164,165,166,167,168,169,170,172,173,174,183,184,185,186,187,188,189,190,191,192,0

#Whether or not to create the default craft type files on plugin enable.
WriteDefaultCraft: true

#Require eggs to fire aa guns?
RequireAmmo: false
