name: ${name}
main: ${groupId}.${artifactId}.${name}
version: ${version}
authors: [Maximuspayne, keough99, Pocketkid2]
depend: [WorldGuard, WorldEdit, Vault]

commands:
  navycraft:
    aliases: [nc]
    description: Displays navycraft status message.
  navycraft help:
    aliases: [nc_help]
    description: Shows help for navycraft.
  shipyard:
    aliases: [yard, sy]
    description: Displays shipyard status message.
  shipyard help:
    aliases: [yard_help, sy_help]
    description: Shows help for shipyard.
  rank:
    description: Shows player rank and their exp.
  rank help:
    description: Shows help for ranks.
  volume:
    description: Displays volume status message.
  volume help:
    description: Shows help for volume.
