name: NavyCraft
main: com.maximuspayne.navycraft.NavyCraft
version: 2.0.1-SNAPSHOT
authors: [keough99, Pocketkid2, Maximuspayne]
depend: [WorldGuard,WorldEdit,Essentials,GroupManager]

commands:
   navycraft:
      description: Ship and other vehicle based commands
      usage:
           /<command>
   ship:
      description: Ship
   aircraft:
      description: Aircraft
   submarine:
      description: Submarine